### ISSUE TITLE
Aurora conflicts with EconomyShopGUI

### ISSUE THREAD

**Issue by Nahciak** [AuroraUniverse/AuroraUniverse#5]
console log

[22:42:27 INFO]: [EconomyShopGUI] Enabling EconomyShopGUI v5.2.2
[22:42:27 INFO]: [EconomyShopGUI] lang-pl.yml jest używany jako plik językowy.
[22:42:27 INFO]: [EconomyShopGUI] Shops.yml został znaleziony!
[22:42:27 INFO]: [EconomyShopGUI] Sections.yml został znaleziony!
[22:42:27 ERROR]: Error occurred while enabling EconomyShopGUI v5.2.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "singular" is null
at me.gypopo.economyshopgui.providers.economys.VaultEconomy.formatSingular(VaultEconomy.java:68) ~[EconomyShopGUI-5.2.2.jar:?]
at me.gypopo.economyshopgui.providers.economys.VaultEconomy.setup(VaultEconomy.java:31) ~[EconomyShopGUI-5.2.2.jar:?]
at me.gypopo.economyshopgui.util.EconomyHandler.initProvider(EconomyHandler.java:90) ~[EconomyShopGUI-5.2.2.jar:?]
at me.gypopo.economyshopgui.util.EconomyHandler.loadDefaultEconomy(EconomyHandler.java:79) ~[EconomyShopGUI-5.2.2.jar:?]
at me.gypopo.economyshopgui.util.EconomyHandler.registerPaymentSolutions(EconomyHandler.java:30) ~[EconomyShopGUI-5.2.2.jar:?]
at me.gypopo.economyshopgui.EconomyShopGUI.onEnable(EconomyShopGUI.java:151) ~[EconomyShopGUI-5.2.2.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:42:27 INFO]: [EconomyShopGUI] Disabling EconomyShopGUI v5.2.2

**Comment by karlovm** [comment]
Fixed in 0.8.0.0
